dist: xenial

# Install the snap prerequisites
addons:
  snap:
    - hugo

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    
# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - git submodule init
  - git submodule update themes/fdc-theme-hugo
  - hugo --theme=fdc-theme-hugo

# Deploy to GitHub pages
deploy:
  if: fork = false AND branch = master
  provider: pages
  skip_cleanup: true
  repo: futminna-dev-circle/futminna-dev-circle.github.io
  target_branch: master
  github_token: $GITHUB_TOKEN
  local_dir: public
